### ISSUE TITLE
Default action when tvshow is clicked

### ISSUE THREAD

**Issue by thorus90** [yanncam/KodiWebPortal#10]
Hi,

At the moment if I want to see what series a tvshow has, I have to click on the Info-symbol in the bottom of the tvshow.

I would like to click anywhere on the tvshow that the popup is displayed which shows the informations about the tvshow.

I guess some other users, would like to have another default action when the tvshow is click, or even none. So perhaps making it configurable would be the most generic option.

Thanks!!!

**Comment by yanncam** [comment]
Hello,

Can you try the 1.1.8 version ? (commit https://github.com/yanncam/KodiWebPortal/commit/75129b9d02d8715a5c476838ff01a12b93adf4a5).

Now the tvshow description div is opened when you click anywhere on the tvshow main entry. But the mouse-cursor icon is diplayed only on "info" button.

Sincerely,

**Comment by thorus90** [comment]
Hi,

Thank you, works like charm!

Regards,
