### ISSUE TITLE
bug from version 1.1.1 Movies

### ISSUE THREAD

**Issue by boing86** [yanncam/KodiWebPortal#11]
I found another bug, I think it's the same as here:
https://github.com/yanncam/KodiWebPortal/issues/9

Version 1.1.0
![image](https://user-images.githubusercontent.com/24889283/32180437-41dca954-bd92-11e7-9d10-9495f6c73967.png)

Version 1.1.1 and +
![image](https://user-images.githubusercontent.com/24889283/32180443-4c212c6e-bd92-11e7-9601-032cf5e5ce5e.png)

**Comment by yanncam** [comment]
Hello,

I can't reproduce your bug. Can you re-scrap your library and check again ?

Sincerely,

**Comment by boing86** [comment]
Hello

My test system is:
VM - Kodi 17.5 on ubuntu17.04
VM - Synology DSM 6.1.3 U4
KodiWebPortal 1.1.6

- New DB created on Maria DB10
- scrap 3 movies

-> KodiWebPortal shows no details

- re-scrap or wait about 1min
-> KodiWebPortal shows details

- New DB created on Maria DB5
- scrap 3 movies

-> KodiWebPortal no details

- re-scrap or wait about 1min
-> KodiWebPortal details


Hautpsystem:
Synology DSM 6.1.3 U8
Kodi17.5 on Win10

On the master DB I have 400+ movies, it does not work with re-scrap.
I try to refresh it individually.

What confuses me is that it works with an old version.

After the whole test this morning I think that it is not a mistake of KodiWebPortal.

Sorry for this issue

greeting

**Comment by boing86** [comment]
Hello

If I use play / stop on the films without details, the details are there after that.

The re-scrap had not helped and single updating had only partially helped.

Greeting

**Comment by yanncam** [comment]
Hello,

I think it's now fixed (problem with a LEFT JOIN SQL request since streamdetails have been added).

Can you try the 1.1.7 version (commit : https://github.com/yanncam/KodiWebPortal/commit/51c192a8ca526e9b6bc17221afc3364aba19a734).

Sincerely,

**Comment by boing86** [comment]
Hello

V1.1.7 and 1.1.8 wokrs 

thanks a lot
