### ISSUE TITLE
Download files with ä ö ü dos not work

### ISSUE THREAD

**Issue by boing86** [yanncam/KodiWebPortal#14]
Version 1.2.0

I found an error while downloading.
Files that have an ao in the filename can not be uploaded.

Everyone else is going.

![image](https://user-images.githubusercontent.com/24889283/40474233-c726a350-5f3e-11e8-8848-dbcdfe4a2622.png)

**OK**
Datei Pfad : 
/volume1/video/Filme/Die Vollpfosten - Never Change a Losing Team 2012/Die Vollpfosten - Never Change a Losing Team 2012.mp4

**NOK**
Datei Pfad : 
/volume1/video/Filme/3 Türken und ein Baby 2015/3 Türken und ein Baby 2015.mp4|utf8=0

**Comment by boing86** [comment]
I found a solution
add the following lines in dl.php

before "header (" X-Sendfile: $ path ");"

```
			//kill |utf8=0 from filepath and filename 
			$path=str_replace('|utf8=0', '', $path);
			$data["strFileName"]=str_replace('|utf8=0', '', $data["strFileName"]);
```

**Comment by yanncam** [comment]
Hello @boing86,

Thank you for this issue, your feedback, tests and your commits, I've accepted the merged request :) !

Sincerely,
