### ISSUE TITLE
Ldap Login error

### ISSUE THREAD

**Issue by boing86** [yanncam/KodiWebPortal#17]
I found an error with the LDAP login.

Users with **-** or **_** in the username can not log in.
I've edited the following in file functions.php line 52, but am not sure if it causes any other problems.

```
if (preg_match ( "/ ^ [a-zA-Z \ s \ _ \ s \ -] + $ / ', $ user)) {
```

Passwords with the **+** sign also do not work. The password is not transmitted correctly to the functions.php

friendly greetings

**Comment by boing86** [comment]
![image](https://user-images.githubusercontent.com/24889283/41262629-3532653a-6de2-11e8-8b6d-cc457fc76e37.png)

Print user and passwort from functions.php

**Comment by boing86** [comment]
login.php

> <script type="text/javascript">
> 	function login(user, passwd){
**> 		passwd=encodeURIComponent(passwd)**
> 		$.ajax({

the sing + in the password work with this line

**Comment by yanncam** [comment]
Hello @boing86,

Thank you for this issue, your feedback, tests and your commits, I've accepted the merged request :) !

Sincerely,
