### ISSUE TITLE
Multiple Movie and TV Shows path in config.php

### ISSUE THREAD

**Issue by mmagnetix** [yanncam/KodiWebPortal#18]
Hi,

Question regarding Movie and TV Show path's in config.php

define("NAX_MOVIES_LOCAL_PATH", "/volume1/movies/"); // Local path where are movies
define("NAX_MOVIES_REMOTE_PATH", "smb://x.x.x.x/movies/"); // Location of movies in Kodi DB
define("NAX_TVSHOW_LOCAL_PATH", "/volume1/TV-Show/"); // Local path where are TVshow
define("NAX_TVSHOW_REMOTE_PATH", "smb://x.x.x.x/TV-Show/"); // Location of TVshow in Kodi DB

is it possible to enter more Movies and TV Show path's in the config.php
for example ended tv shows located at /volume1/tv-show-ended or movies1 .. movies3

Regards,
Magnetix

**Comment by yanncam** [comment]
Hello,

Sorry but it's not possible at this time to add several differents paths for TVShow or Movies via the config.php file.

But, you can create symbolic link (symlink) from the main path to point to other location I think.

Sincerely,

**Comment by mmagnetix** [comment]
OK.
