### ISSUE TITLE
TV Series no Media Info visible

### ISSUE THREAD

**Issue by mmagnetix** [yanncam/KodiWebPortal#19]
Hi,

With movies the media info is included. Outstanding that you added this feature on my request :)
but it is not visible in the TV series when I press Info for the specific S01E01. would be nice to quickly check the Quality of the TV-Serie.

Thanks in Advance.
Magnetix

**Comment by mmagnetix** [comment]
Example: 

Realisator : Juan Carlos Fresnadillo
Scriptwriter : Elizabeth Kruger / Craig Shapiro / Matt JL Wheeler
Studio : CBS
Note : 8791
File path : /volume1/*blahdieblah*/Salvation/Season 01/Salvation - S01E01 - Pilot.mkv
Media Info :
File size : 2.1 GB

Media info is blank....

Regards,
Magnetix

**Comment by yanncam** [comment]
Hi @mmagnetix,

Hum, do you use the latest version of KWP ?

On my side, `Media Info` is not blank like you can see on the attachment.

![capture](https://user-images.githubusercontent.com/11797034/44954891-27310f00-aeaa-11e8-8597-64580830a9af.PNG)

Sincerely,

**Comment by mmagnetix** [comment]
Hi, 

using v1.2.0 of KWP
checking the git source v1.2.0 is the latest.

strange......

Regards,
Magnetix

**Comment by mmagnetix** [comment]
Hi,

I might have found the problem. But not sure. 

By retrieving the mediainfo Could you send me query example? So I can check if in the database tables the mediainfo is missing.

If so then It could be a scraper issue.

Thanks,
Magnetix

**Comment by yanncam** [comment]
Hello,

I just have echo'ed the SQL query for a detailsTvShow:

```
SELECT tvshow_view.c00 AS tvshowTitleFR, tvshow_view.c01 AS tvshowSynopsis, season_view.episodes AS seasonNbEpisodes, season_view.season AS seasonIdseason, season_view.premiered AS seasonPremiered, season_view.playCount AS seasonPlayCount, episode_view.c13 AS episodeIdepisode, episode_view.c00 AS episodeTitle, episode_view.c10 AS episodeRealisator, episode_view.c04 AS episodeScriptwriter, episode_view.c03 AS episodeNote, episode_view.c01 AS episodeSynopsis, episode_view.playCount AS episodePlayCount, episode_view.studio, episode_view.strPath, episode_view.strFileName, episode_view.idEpisode, episode_view.idFile, ExtractValue(tvshow_view.c06,'/thumb[@season="-1"]') AS tvshowThumb0, MAX(streamdetails.strVideoCodec) AS streamStrVideoCodec, MAX(streamdetails.iVideoWidth) AS streamIVideoWidth, MAX(streamdetails.iVideoHeight) AS streamIVideoHeight, MAX(streamdetails.strAudioCodec) AS streamStrAudioCodec, MAX(streamdetails.iAudioChannels) AS streamIAudioChannels FROM tvshow_view, season_view, episode_view LEFT JOIN streamdetails ON episode_view.idFile=streamdetails.idFile WHERE tvshow_view.idShow=:id AND tvshow_view.idShow=season_view.idShow AND season_view.idShow=episode_view.idShow AND season_view.season=episode_view.c12 GROUP BY episode_view.idFile, streamdetails.idFile ORDER BY season_view.idSeason, CAST(episode_view.c13 as SIGNED INTEGER) ASC;
```

Try this query (by changing the `:id` by a TVShow ID) directly on your phpMyAdmin to debug.

Sincerely,

**Comment by mmagnetix** [comment]
Hi,
 
Checking the tables. will report feedback. and thanks for the query. 

Regards,
Magnetix

**Comment by mmagnetix** [comment]
Hi,

analyzed TV-Show Tables, 

streamStrVideoCodec, streamIVideoWidth, streamIVideoHeight, streamStrAudioCodec, streamIAudioChannels

**TV-Show tables were the codec information is retrieved by the scraper:**

![tvshow-codec-info](https://user-images.githubusercontent.com/26583441/45253285-1e868000-b365-11e8-945b-99135e2bfabd.png)

**TV-Show tables were NO codec information is retrieved by the scraper:**

![tvshow-no-codec-info](https://user-images.githubusercontent.com/26583441/45253306-60afc180-b365-11e8-9a30-12d6be9931aa.png)

Problem is CLEAR. no bug in KWP but MariaDB tables with NO data codec,streamdata.
caused by the TV Show scraper.
 
Issue can be closed. since it is a scraper, local issue. buggy scraper!!

fixing TV Shows one by one is for now the only solutions by re-collecting the data. 

Regards,
Magnetix

**Comment by yanncam** [comment]
Hello @mmagnetix,

Thanks for your feedback and to have take the time to do some tests !
Ok, noted for the buddy scraper.
I close the issue,

Have a nice day,
