### ISSUE TITLE
No artwork for TVShows

### ISSUE THREAD

**Issue by danmed** [yanncam/KodiWebPortal#22]
HI,

Just got this working on a Ubuntu web server.. movies are all working great however when i switch to TV shows, there is no artwork...

**Comment by yanncam** [comment]
Hello,

Could you check your apache logs/errors and your browser's console logs/erros please ?

Sincerely,

**Comment by danmed** [comment]
I've just had a look in my MySQL database and my columns C6 and C11 (Where it appears you pull the Artwork from) are empty...

Everything works great in Kodi so not sure why it's not populated those

**Comment by yanncam** [comment]
Ok so it's a scrapper issue in your Kodi side I think. Check your scrapper configuration in Kodi :)

**Comment by danmed** [comment]
But it works fine.. My Kodi instances are all fully populated with TV Artwork.. I've no idea why it would not put those URL's in the DB.

**Comment by yanncam** [comment]
Perhaps you have pictures in the folder of each tvshow, so Kodi doesn't populate them (as URL) in the database ?

Picture like:

* fanart.jpg
* poster.jpg
* season-all-poster.jpg
* season-specials-poster.jpg
* season01-banner.jpg
* season01-poster.jpg
* tvshow.nfo

Etc.

**Comment by danmed** [comment]
Yep, just came to that conclusion my self.. Any way for you to build this in?

**Comment by yanncam** [comment]
Try to delete all metadata file of one tvshow folder not indexed in Kodi (*.jpg, *.nfo).
Then launch an update of your Kodi database and check in MySQL if URLs are fullfilled.

I have found this topic (https://forum.kodi.tv/showthread.php?tid=207085) but I haven't see this problem myself, sorry :s

**Comment by yanncam** [comment]
Hello,

I close this issue, consider it as resolved (no new feedback).

Sincerely,
