### ISSUE TITLE
Exposure of username/password in file path

### ISSUE THREAD

**Issue by luckyyvt** [yanncam/KodiWebPortal#23]
In my database, the filename smb:// paths have the username and password embedded in them.  It might be wise to filter those out in the function.php script with a simple regex similar to this:
$path = preg_replace("#(?<=:/)[^:@]+(:[^@]+)?(?=@)#","...",$path)

This way a viewer only sees "..." instead of exposing the username and password.

Otherwise a great script, thanks!

**Comment by yanncam** [comment]
Hello @luckyyvt,

It's an excellent suggestion, thank you very much for this issue and your improvment of KWP !

Your regex is in place in the commit https://github.com/yanncam/KodiWebPortal/commit/3fa4e52edafb445bffc28ef5f86790cbdbda216c

Can you check and tell me if it's good on your side ?

Sincerely,
