### ISSUE TITLE
No tvshow covers displayed

### ISSUE THREAD

**Issue by gnuranza** [yanncam/KodiWebPortal#26]
I set up my kodi web portal 1.2.2 based on Kodi 18.5 and it works fine except for the tvshow section that doesn't show at all any cover. I catch Failed to load resource: net::ERR_NAME_NOT_RESOLVED nopicture/1. Can you help me?

**Comment by j1pe** [comment]
Hey,
I found the problem but not the solution.
For my part I have some series that display the "rounded fanart" and no other.
So I compared column c11 of my db.

I realized that if there were several "/fanart" in the table, the site won't load the image and will display "images/fanart-onerror.png".

If you leave only the part with the first "/fanart", the image is displayed well.

example:

Incorrect entry:

`<fanart url="http://image.tmdb.org/t/p/"><thumb dim="3840x2160" preview="w780/xETbCo8l06poxFUgbtaUeKmLadz.jpg">original/xETbCo8l06poxFUgbtaUeKmLadz.jpg</thumb><thumb dim="3840x2160" preview="w780/6XyIkXeb5ZjaDNrghmkOQypCY1U.jpg">original/6XyIkXeb5ZjaDNrghmkOQypCY1U.jpg</thumb><thumb dim="1920x1080" preview="w780/zLXh4zDGxH7yAwNkWR1LAocKlZb.jpg">original/zLXh4zDGxH7yAwNkWR1LAocKlZb.jpg</thumb><thumb dim="1920x1080" preview="w780/xspRl7vOLPEi9fPOt0bPXaPWQEn.jpg">original/xspRl7vOLPEi9fPOt0bPXaPWQEn.jpg</thumb><thumb dim="1920x1080" preview="w780/17j1k1cqFL9a57h6wPMPCXh5JoV.jpg">original/17j1k1cqFL9a57h6wPMPCXh5JoV.jpg</thumb><thumb dim="2222x1250" preview="w780/bebFVt9OqrvYxVIZHlzPG1A0Hjx.jpg">original/bebFVt9OqrvYxVIZHlzPG1A0Hjx.jpg</thumb><thumb dim="1280x720" preview="w780/ckfDLOjl1xu1TOgiBEjrrHorKcH.jpg">original/ckfDLOjl1xu1TOgiBEjrrHorKcH.jpg</thumb><thumb dim="2263x1273" preview="w780/A6I3M4MIA2Pi2gS6vGdg2eVlVXT.jpg">original/A6I3M4MIA2Pi2gS6vGdg2eVlVXT.jpg</thumb><thumb dim="1920x1080" preview="w780/tNeWJ8KlBHR3GVFqbme7IvxNkGl.jpg">original/tNeWJ8KlBHR3GVFqbme7IvxNkGl.jpg</thumb><thumb dim="1920x1080" preview="w780/rXiVoX5oYVlA2m1zPu64YhaWuTM.jpg">original/rXiVoX5oYVlA2m1zPu64YhaWuTM.jpg</thumb><thumb dim="3598x2024" preview="w780/g7JCGe4BqD3iWJYvc6rtfUKYtyB.jpg">original/g7JCGe4BqD3iWJYvc6rtfUKYtyB.jpg</thumb><thumb dim="1920x1080" preview="w780/wo1ZWLU3thURIRw5V9Fll5y7S8B.jpg">original/wo1ZWLU3thURIRw5V9Fll5y7S8B.jpg</thumb><thumb dim="1280x720" preview="w780/x9iT7xecf7axa9HeSNf0hBn0kYg.jpg">original/x9iT7xecf7axa9HeSNf0hBn0kYg.jpg</thumb><thumb dim="3840x2160" preview="w780/d3JfSp20mekx7o2aTqJUhcAfYNo.jpg">original/d3JfSp20mekx7o2aTqJUhcAfYNo.jpg</thumb><thumb dim="2048x1152" preview="w780/kaglh4xh7OOMAsfCNnsswcF4Fh4.jpg">original/kaglh4xh7OOMAsfCNnsswcF4Fh4.jpg</thumb><thumb dim="1280x720" preview="w780/qqIFDstqXuiw6vc3NbYrU9ikORo.jpg">original/qqIFDstqXuiw6vc3NbYrU9ikORo.jpg</thumb></fanart><fanart><thumb preview="https://assets.fanart.tv/preview/tv/332331/showbackground/altered-carbon-5a7884f8201cf.jpg">https://assets.fanart.tv/fanart/tv/332331/showbackground/altered-carbon-5a7884f8201cf.jpg</thumb><thumb preview="https://assets.fanart.tv/preview/tv/332331/showbackground/altered-carbon-5e529c3da2d4d.jpg">https://assets.fanart.tv/fanart/tv/332331/showbackground/altered-carbon-5e529c3da2d4d.jpg</thumb><thumb preview="https://assets.fanart.tv/preview/tv/332331/showbackground/altered-carbon-5a7eb24732d5f.jpg">https://assets.fanart.tv/fanart/tv/332331/showbackground/altered-carbon-5a7eb24732d5f.jpg</thumb><thumb preview="https://assets.fanart.tv/preview/tv/332331/showbackground/altered-carbon-5a7eb2474e77a.jpg">https://assets.fanart.tv/fanart/tv/332331/showbackground/altered-carbon-5a7eb2474e77a.jpg</thumb><thumb preview="https://assets.fanart.tv/preview/tv/332331/showbackground/altered-carbon-5a7eb2475aa24.jpg">https://assets.fanart.tv/fanart/tv/332331/showbackground/altered-carbon-5a7eb2475aa24.jpg</thumb><thumb preview="https://assets.fanart.tv/preview/tv/332331/showbackground/altered-carbon-5a7eb2472aad5.jpg">https://assets.fanart.tv/fanart/tv/332331/showbackground/altered-carbon-5a7eb2472aad5.jpg</thumb><thumb preview="https://assets.fanart.tv/preview/tv/332331/showbackground/altered-carbon-5a7eb247414a3.jpg">https://assets.fanart.tv/fanart/tv/332331/showbackground/altered-carbon-5a7eb247414a3.jpg</thumb><thumb preview="https://assets.fanart.tv/preview/tv/332331/showbackground/altered-carbon-5ae0a64739631.jpg">https://assets.fanart.tv/fanart/tv/332331/showbackground/altered-carbon-5ae0a64739631.jpg</thumb><thumb preview="https://assets.fanart.tv/preview/tv/332331/showbackground/altered-carbon-5ae2f59008392.jpg">https://assets.fanart.tv/fanart/tv/332331/showbackground/altered-carbon-5ae2f59008392.jpg</thumb><thumb preview="https://assets.fanart.tv/preview/tv/332331/showbackground/altered-carbon-5ae2f59011058.jpg">https://assets.fanart.tv/fanart/tv/332331/showbackground/altered-carbon-5ae2f59011058.jpg</thumb><thumb preview="https://assets.fanart.tv/preview/tv/332331/showbackground/altered-carbon-5e5a6571afe0d.jpg">https://assets.fanart.tv/fanart/tv/332331/showbackground/altered-carbon-5e5a6571afe0d.jpg</thumb><thumb preview="https://assets.fanart.tv/preview/tv/332331/showbackground/altered-carbon-5a778426ee3c4.jpg">https://assets.fanart.tv/fanart/tv/332331/showbackground/altered-carbon-5a778426ee3c4.jpg</thumb></fanart>`

Correct entry:

`<fanart url="http://image.tmdb.org/t/p/"><thumb dim="3840x2160" preview="w780/xETbCo8l06poxFUgbtaUeKmLadz.jpg">original/xETbCo8l06poxFUgbtaUeKmLadz.jpg</thumb><thumb dim="3840x2160" preview="w780/6XyIkXeb5ZjaDNrghmkOQypCY1U.jpg">original/6XyIkXeb5ZjaDNrghmkOQypCY1U.jpg</thumb><thumb dim="1920x1080" preview="w780/zLXh4zDGxH7yAwNkWR1LAocKlZb.jpg">original/zLXh4zDGxH7yAwNkWR1LAocKlZb.jpg</thumb><thumb dim="1920x1080" preview="w780/xspRl7vOLPEi9fPOt0bPXaPWQEn.jpg">original/xspRl7vOLPEi9fPOt0bPXaPWQEn.jpg</thumb><thumb dim="1920x1080" preview="w780/17j1k1cqFL9a57h6wPMPCXh5JoV.jpg">original/17j1k1cqFL9a57h6wPMPCXh5JoV.jpg</thumb><thumb dim="2222x1250" preview="w780/bebFVt9OqrvYxVIZHlzPG1A0Hjx.jpg">original/bebFVt9OqrvYxVIZHlzPG1A0Hjx.jpg</thumb><thumb dim="1280x720" preview="w780/ckfDLOjl1xu1TOgiBEjrrHorKcH.jpg">original/ckfDLOjl1xu1TOgiBEjrrHorKcH.jpg</thumb><thumb dim="2263x1273" preview="w780/A6I3M4MIA2Pi2gS6vGdg2eVlVXT.jpg">original/A6I3M4MIA2Pi2gS6vGdg2eVlVXT.jpg</thumb><thumb dim="1920x1080" preview="w780/tNeWJ8KlBHR3GVFqbme7IvxNkGl.jpg">original/tNeWJ8KlBHR3GVFqbme7IvxNkGl.jpg</thumb><thumb dim="1920x1080" preview="w780/rXiVoX5oYVlA2m1zPu64YhaWuTM.jpg">original/rXiVoX5oYVlA2m1zPu64YhaWuTM.jpg</thumb><thumb dim="3598x2024" preview="w780/g7JCGe4BqD3iWJYvc6rtfUKYtyB.jpg">original/g7JCGe4BqD3iWJYvc6rtfUKYtyB.jpg</thumb><thumb dim="1920x1080" preview="w780/wo1ZWLU3thURIRw5V9Fll5y7S8B.jpg">original/wo1ZWLU3thURIRw5V9Fll5y7S8B.jpg</thumb><thumb dim="1280x720" preview="w780/x9iT7xecf7axa9HeSNf0hBn0kYg.jpg">original/x9iT7xecf7axa9HeSNf0hBn0kYg.jpg</thumb><thumb dim="3840x2160" preview="w780/d3JfSp20mekx7o2aTqJUhcAfYNo.jpg">original/d3JfSp20mekx7o2aTqJUhcAfYNo.jpg</thumb><thumb dim="2048x1152" preview="w780/kaglh4xh7OOMAsfCNnsswcF4Fh4.jpg">original/kaglh4xh7OOMAsfCNnsswcF4Fh4.jpg</thumb><thumb dim="1280x720" preview="w780/qqIFDstqXuiw6vc3NbYrU9ikORo.jpg">original/qqIFDstqXuiw6vc3NbYrU9ikORo.jpg</thumb></fanart>`


So I looked at the settings on my scraper and I unchecked the box to get the Fanart from fanart.tv.

After that I have most of the background images but no poster.

I hope this helps.

**Comment by j1pe** [comment]
I solved the problem by modifying the file:

- function.php
- tvshow.php

In function.php line 371 before modification:
`$fanart = $data["fanartURL"].$data["fanartValue"];`

After modification:
```
if (!empty($data["fanartURL"]) && !empty($data["fanartValue"]) && (!preg_match ('/https?:\///i',$data["fanartValue"]) {
			$fanart = $data["fanartURL"].$data["fanartValue"];
		} else {
			$fanart = $data["fanartURL2"];
		}
```

In tvshow.php:
line 59 before:
`ExtractValue(c06,'/thumb[@season=\"-1\"]') AS thumb,`
Line 59 next:
`ExtractValue(c06,'/thumb [position()=1]') AS thumb,`

adding the line below line 61:
`ExtractValue(c11,'/fanart/thumb [position()=1]') AS fanartURL2`

For me it works with multiple scrapers.

**Comment by yanncam** [comment]
Hello,

I have merged the pull request of @j1pe with these fix !

Thank you (and sorry for the time...).
