### ISSUE TITLE
Sort by name

### ISSUE THREAD

**Issue by j1pe** [yanncam/KodiWebPortal#28]
First of all, thank you very much for the job, it's a great solution!!

I wanted to know if it was possible to sort the information by name and not by the date of entry in the database?

I search in the files but find nothing.

Thanks again for the work done.

**Comment by yanncam** [comment]
Hello @j1pe,

When you display all movies entries, there are sorted by `dateAdded` DESC.
When you do a search by year or keyword for example, results are sorted by name (title).

I have not planned to integrate a customizable sorting parameter for now (but I keep the idea in mind).

If you want to change the sorting parameter for your deployment, edit the `index.php` file at line **87** :

From:
```
			FROM " . NAX_MOVIE_VIEW . " ORDER BY dateAdded DESC LIMIT $offset," . DEFAULT_ENTRIES_DISPLAY . ";"; 
```

to this, for a sort by french title:
```
			FROM " . NAX_MOVIE_VIEW . " ORDER BY c00 LIMIT $offset," . DEFAULT_ENTRIES_DISPLAY . ";"; 
```

or to this, for a sort by english title:
```
			FROM " . NAX_MOVIE_VIEW . " ORDER BY c01 LIMIT $offset," . DEFAULT_ENTRIES_DISPLAY . ";"; 
```

Sincerely,

**Comment by j1pe** [comment]
Thank you, that's exactly what I wanted.

If the user could do it himself it would be even better but it's already great like that.
