### ISSUE TITLE
Scrolling not possible on browser in 1440p Resolution

### ISSUE THREAD

**Issue by Hornochs** [yanncam/KodiWebPortal#32]
Hey there,
first thanks for this project! But I found a "funny" bug. When I open up the site in a 1080p screen everything is okay, I scroll down und the next movies are getting loaded. IF I do this on my 1440p screen 16 results wil be displayed, but so much room at the end, that no scollring is possible and therefore no new results will be loaded 😅

Any Idea how I could fix that? Can to then a pull request for you if I tested it on my site.

Cheers,
Hornochs

**Comment by yanncam** [comment]
Hello @Hornochs,

Thanks for your feedback :) !
This "bug" is already known here : https://github.com/yanncam/KodiWebPortal/issues/20

So I quote myself for mitigate this behaviour:

- By default, ``DEFAULT_ENTRIES_DISPLAY`` is set to 16
- With a wide screen with high resolution (2560x1600), 16 entries printed by default isn't enough to display the scrollbar of the browser's window. The behaviour can be simulated by un-zooming in firefox or chrome the main page of KWP.
- The loading mecanism of the next 16 entries is triggered on the ``event $(window).scroll()`` in the script.js file
- So if your screen is too wide and no-scroll is displayed at the first time, there is no chance to trigger this event => the bug.

To mitigate this behaviour, you can:

- Adjust the ``DEFAULT_ENTRIES_DISPLAY`` value to a bigger one (20, 32 as example, depending of your screensize) to force an initial scrollbar on the window
- Or I can add a "button" in the bottom-right-corner with an event "onclick" to "load more result" (same code as the one trigger by the ``$(window).scroll())``

Sincerely,
