### ISSUE TITLE
Feature request: Is it possible to add actors and directors ?

### ISSUE THREAD

**Issue by PAOK1926** [yanncam/KodiWebPortal#33]
hello, 

Is it possible to add actors and directors in the front synopsis of every movie ?

and another one request, after i search for a director, results are sorted by name and not by year..

**Comment by yanncam** [comment]
Hello @PAOK1926,

The _director_ and _actors_ details are available when you click on the "Information / Description" button on the bottom of each movie displayed on the main page.

If I display all these information (all the actors and director) directly under the synopsys on the main page, it will be very verbose. So only the movie title and synopsys are displayed. For more information you have to click on "Information / Description" button.

For your second question, there are two type of sorting the results:

- When you go to the main page of movies without any filter, movies are displayed from the more recent added in Kodi to the oldest.
- When you use the filter bar (any kind of criteria such as _year_ or _director_ or _nationality_), the results are automatically sorted alphabeticaly and this sort is hardcoded. Indeed, if you choose a _year_ filter (like 2021), it doesn't make sens to sort results by year.

Sincerely,
