### ISSUE TITLE
See what episodes/movies are already watched

### ISSUE THREAD

**Issue by thorus90** [yanncam/KodiWebPortal#4]
First of all, thanks for your work. Installation worked like charm.

Is it possible that you could a add the information if the movie or episode was already watched? Just as in kodi, where the already watched episodes and movies are checked.

I want to use the webinterface to know which episodes I already watched when I'm on a business trip.

Thanks!

**Comment by yanncam** [comment]
Hello,

Thanks for your feedback :) !

As describe in the README of the project (in the footer), yes, it's in the roadmap to add a "star" or a "tick" for each movies/tvshows to know if you have already watched it.

But as KodiWebPortal can be multi-user (through LDAP authentication as example), I need to store in a third-party table in database the status "seen" or "not seen" for each user.

Currently, KodiWebPortal doesn't implement his how database / tables, but it will be added for the future.

For the moment, I can propose to you to add a simple new configuration variable like `$showWatchedStatus=true` or false in the `config.php` file and display for all users the status watched/unwatched based on the Kodi's database attribute.

I keep you in touch when this update will be done ;) !

Sincerely,

**Comment by boing86** [comment]
Multiple user watch status is difficult.
When I set up the database according to this guide.
https://forum.kodi.tv/showthread.php?tid=196821&pid=2515045#pid2515045
and other table names, it would not work anymore.

**Comment by yanncam** [comment]
Hello @boing86,

Yes, I agree with you.
I think I will *cheat* in KodiWebPortal (in the future) with this kind of behaviour:

* When the owner user log into KodiWebPortal (same user as the main profile in Kodi), he can see the watched status (a star or a tick) in the corner of each movies / tvshows.
* When another user (my wife as example) log into KodiWebPortal, she can see if she has already get a movie or tvshow by the another icon (but it's based on *download* / *not downloaded yet* status when she is at the hotel as example).
* Finaly, it's possible to add a little button on each movie / tvshow for the user to clic and pass a specific movie / tvshow as *watched* or *unwatched* (these status will be stored in third database specific for KodiWebPortal).

Do you have any others ideas / suggestions for future evolutions?

Sincerely and thanks for your comment,

**Comment by thorus90** [comment]
Hi,

Watch status for single user which has to have the same name as the main profile in kodi is totally fine by me!

I would wish for if I pass a movie / tvshow as watched it would update the actual kodi database.

When I'm on a business trip I can watch my tvshows locally and mark them as watched in kodi web portal, and when at home I can simply continue watchin in kodi, without having the need to look into kodi web portal where I have left off.

I don't know for sure, but incrementing the playCount by 1 should already do the trick?

Thanks for considering my ideas!

**Comment by yanncam** [comment]
Hello @thorus90,

From Kodi database, I have seen two things:

* playCount column has a value when you have seen at least one time a media (else NULL value). This integer value is incremented for each full-watched movie.
* lastPlayed column contains a timestamp indicating the last played date of the current movie.

So, you can have:

* playCount == NULL and laspPlayed == NULL : totally new media unwatched
* playCount == NULL and laspPlayed == some date : media watching started but unfinished (boring movie?)
* playCount == N (with N > 0) and laspPlayed == some date : media watch at least 1 time

I have started to implement this behaviour with 3 icons:

* Watched
* Started
* Unwatched

Then I'll add a button (or a click event on this icon) to change the state from KodiWebPortal in Kodi DB between **watched** or **unwatched** value.

There are several tests to do on my side:

* Can I just set the playCount to NULL or 0 and set lastPlayed to NULL to change the status of a movie to **unwatched** ?
* Can I just set the playCount to 1 and lastPlayed to the current date to change the status of a movie to **watched** ?

I keep you in touch when I will commit these evolutions,

Sincerely,

**Comment by yanncam** [comment]
Ok, so, I have implemented the **watched status** for movies (only) for the moment ; without the possibility to change the **watched status** directly in the Kodi DB (always for the moment ;)).

I display over each poster of movie, in the top-left corner one of these icons:

![watched](https://user-images.githubusercontent.com/11797034/31720452-ecc70650-b416-11e7-8aa8-9107b43b4d4a.png)

For movies with playCount > 0 (watched entirely at least one time).

![started](https://user-images.githubusercontent.com/11797034/31720462-f3f2deb8-b416-11e7-8f5d-4a1484b1d96e.png)

For movies started to watch but not finished (playCount == NULL and lastPlayed == some date).

![unwatched](https://user-images.githubusercontent.com/11797034/31720472-f8ac0f38-b416-11e7-9fc6-23ce31e1bd8b.png)

For movies totally unwatched (playCount == NULL and laspPlayed == NULL).

I'll do the same thing for tvshows and keep you informed,

Sincerely,

**Comment by yanncam** [comment]
Hello all,

Ok, so I have implemented the **watched** / **unwatched** status for all media (movies, tvshows, seasons and episodes).

Finally, only two status were implemented (**watched** / **unwatched**), the **started** status isn't interesting enough. So the implementation is based only on the `playCount` attribute.

For the moment, you can just see what is the status of a media : you can't change the status through KodiWebPortal (watched to unwatched and unwatched to watched). This additionnal feature will be added soon.

I have made several improvement of KodiWebPortal via several commit. The latest version is the 1.1.0 (commit https://github.com/yanncam/KodiWebPortal/commit/d9c359346f323df8fba22e715dcc468bbb99f7b2).

Thank you for your feature request and so the KodiWebPortal improvment !

Keep me informed if this feature works for you.

Have a nice day,

**Comment by thorus90** [comment]
Hi @yanncam ,

Thanks for the quick work, that way I can delete my fork again.

The feature works fine for me.

**Comment by yanncam** [comment]
Perfect :) !

I closed this issue.

Thank you !

**Comment by yanncam** [comment]
Hello,

I've integrated **new button** for each movies/tvshow-episodes to change on-the-fly the **watched / unwatched** status from KodiWebPortal in the Kodi's database directly (v1.2.0 commit https://github.com/yanncam/KodiWebPortal/commit/8b7c10e8872f203e99bbfc56b483e7e7f61f95f6).

Please keep me informed if you encounter any issue.

Sincerely,
