### ISSUE TITLE
Filesize NA

### ISSUE THREAD

**Issue by mmagnetix** [yanncam/KodiWebPortal#6]
Hi,

define("NAX_MOVIES_LOCAL_PATH", "/volume1/video/");	// Local path where are movies
define("NAX_MOVIES_REMOTE_PATH", "nfs://192.168.192.14/video/");	// Location of movies in Kodi DB
define("NAX_TVSHOW_LOCAL_PATH", "/volume1/TV-Series/");	// Local path where are TVshow
define("NAX_TVSHOW_REMOTE_PATH", "nfs://192.168.192.14/TV-Series/");	// Location of TVshow in Kodi DB

The above path in kodi is nfs://192.168.192.14/video/somedirs/blablah.mkv
but filesize is NA ???

**Comment by yanncam** [comment]
Hello,

Could you try with the **smb://** protocol rather than the **nfs://** ?

Your KodiWebPortal is hosted on the same server (NAS Synology) that your medias ?

Do you have any php error/warning ?

Sincerely,

**Comment by mmagnetix** [comment]
Hai,
 
for security reasons and speed I use nfs. (no cifs netbios traffic) The Filesize was never any issue.
I might have found the problem. 

If I look at the information and look at the path+file location it is incorrect displayed.

correct path should be: nfs://ipaddress/content/
incorrect displayed is now nfs:/ipaddress/content/
 
somehow I mis a single '/'

**Comment by yanncam** [comment]
Sorry I don't understand. It's a mistake on your side ? You have forgotten a **/** in your `config.php` ? Or it's a bug in KodiWebPortal ?

On my side I use protocol **smb://** as describe in the sample `config.php` and it works fine with filesize.

**Comment by mmagnetix** [comment]
Hi,

I think it is a bug in the KodiWebPortal. in the above threat I added my config parameters.
but when Pressing the Information button. it reports the filepath like the example is shown. 

File path :
nfs:/192.168.192.14/volume1/video/MKV-720/movie blah (2015)/movie blah (2015).mkv
     ^^-> missing an /

 any idea?

**Comment by mmagnetix** [comment]
I think this is a local problem. Will investigate localy. don´t know why it does not show the filesize right.
rolled back to v1.05 on all versions it does not show. Closing the issue...

**Comment by yanncam** [comment]
Hello,

Try to debug your configuration with this unitary script `test.php` as example:

```
<?php

define("FILESIZE_UNITY", "o");

function showsize($file) {
	$return = "N/A";
	$statBin = "/bin/stat";
    if (strtoupper(substr(PHP_OS, 0, 3)) == 'WIN') {
		if (class_exists("COM")) {
			$fsobj = new COM('Scripting.FileSystemObject');
			$f = $fsobj->GetFile(realpath($file));
			$file = $f->Size;
		} else {
			$file = trim(exec("for %F in (\"" . $file . "\") do @echo %~zF"));
		}
    } elseif (PHP_OS == 'Darwin') {
		$file = trim(@shell_exec("$statBin -f %z " . escapeshellarg($file)));
    } elseif ((PHP_OS == 'Linux') || (PHP_OS == 'FreeBSD') || (PHP_OS == 'Unix') || (PHP_OS == 'SunOS')) {
		$file = trim(@shell_exec("$statBin -t " . escapeshellarg($file) . " | awk '{ print $(NF-14) }'"));
    } else {
		$file = filesize($file);
    }
	$file = intval($file);
	if($file <= 0) {
		$return = "N/A";
    } elseif ($file < 1024) {
		$return = $file . ' ' . FILESIZE_UNITY;
    } elseif ($file < 1048576) {
		$return = round($file / 1024, 2) . ' K' . FILESIZE_UNITY;
    } elseif ($file < 1073741824) {
		$return = round($file / 1048576, 2) . ' M' . FILESIZE_UNITY;
    } elseif ($file < 1099511627776) {
		$return = round($file / 1073741824, 2) . ' G' . FILESIZE_UNITY;
    } elseif ($file < 1125899906842624) {
		$return = round($file / 1099511627776, 2) . ' T' . FILESIZE_UNITY;
    } elseif ($file < 1152921504606846976) {
		$return = round($file / 1125899906842624, 2) . ' P' . FILESIZE_UNITY;
    } elseif ($file < 1180591620717411303424) {
		$return = round($file / 1152921504606846976, 2) . ' E' . FILESIZE_UNITY;
    } elseif ($file < 1208925819614629174706176) {
		$return = round($file / 1180591620717411303424, 2) . ' Z' . FILESIZE_UNITY;
    } else {
		$return = round($file / 1208925819614629174706176, 2) . ' Y' . FILESIZE_UNITY;
    }
	return $return;
}

echo showsize("/etc/passwd");
echo "<br />";
echo showsize("/volume1/movies/movie.avi");

?>
```

Good luck,
