### ISSUE TITLE
Titel height

### ISSUE THREAD

**Issue by boing86** [yanncam/KodiWebPortal#8]
The letter g is truncated in the title.

This change would be necessary in style.css

.details .details-title {
  height: 28px;
}

.entry .title {
  height: 28px;
}

I wanted to change it myself like the language file lang_en.php, but it does not work. That's why I created an issue.

**Comment by yanncam** [comment]
Hello,

It's fixed now, the "g" letter is displayed entirely :) ! (commit https://github.com/yanncam/KodiWebPortal/commit/4b7c9b6688776c5a0d7deff29d10537674274a6c).

Thanks,
