### ISSUE TITLE
mistake from version 1.1.1

### ISSUE THREAD

**Issue by boing86** [yanncam/KodiWebPortal#9]
I have updated the webportal on the Main Kodi DB to 1.1.3. I have noticed Fogeldes:

Something has gone wrong between version 1.1.0 and 1.1.1.
In version 1.1.0 it shows me all episodes
From version 1.1.1 and newer it only shows these episodes, which were once looked at with Kodi.

KodiWebPortal 1.1.0
![image](https://user-images.githubusercontent.com/24889283/31854690-78f69b76-b69d-11e7-9893-4feda9e80cd0.png)

KodiWebPortal 1.1.1 and newer
![image](https://user-images.githubusercontent.com/24889283/31854696-ab1b6474-b69d-11e7-84cb-63b0c49d9616.png)

**Comment by yanncam** [comment]
Oh... It seems to be a big bug indeed.

Between the 1.0.9 and 1.1.1 the main new functionnality is about the **watched** / **unwatched** status and so the **playCount** column retrieved from Kodi's SQL DB (commit concerned : https://github.com/yanncam/KodiWebPortal/commit/d9c359346f323df8fba22e715dcc468bbb99f7b2).

Can you, if possible, check your SQL entries concerning this tvshow on your side, to try to understand why the seasons 2-6 aren't displayed ? **playCount** column contains a good value ?

For information, it's certainly a error in the SQL request in the `getDetailsEntryTvShow()` function in `functions.php`.

Keep me informed, I'll take a look deeper.

Sincerely,

Edit : I think I have found one twshow on my side too, which has the same problem. Only one season is displayed (but there is 10 seasons in the NAS).

**Comment by yanncam** [comment]
Can you try this 1.1.5 version (commit https://github.com/yanncam/KodiWebPortal/commit/5734d1296fed58e2cf71d728cf3e3cc39f658ecf) ?

I think it's fixed.

**Comment by boing86** [comment]
Hello I think he shows me only the series when lastPlayed is not "NULL".
at playCount, the value at all "NULL"

I will test the new version 1.1.5

SELECT `playCount`, `strTitle`, `lastPlayed`,`c12`,`c13` FROM `episode_view` WHERE `strTitle`='Vampire Diaries' AND (`c12`='2' OR `c12`='1') ORDER BY `episode_view`.`c12` ASC

![image](https://user-images.githubusercontent.com/24889283/31862212-701d121c-b73a-11e7-8604-de0df8a27057.png)

**Comment by boing86** [comment]
Yes the version 1.1.5 works well.

Many thanks.

**Comment by yanncam** [comment]
Perfect :) ! I close this issue.

Thanks !
